$(document).ready(function(){$('.spoil').click(function(){var spoil=$(this).next('.content-foto');
	if(spoil.css('display')=='block'){spoil.hide();
	$(this).find('.tire').text('+');
$(this).find('.disp-text').text('Показать фото');
}else{spoil.show();
	$(this).find('.tire').text('–');
$(this).find('.disp-text').text('Скрыть фото');
}});
function getRandom(min,max){var res=Math.floor(Math.random()*(max-min+1)+min);
	if(res<10){return'0'+res;
}else{return res;
}}
var peoplePerDay=8800;
var date=new Date();
var totalPeople=Math.round((peoplePerDay/1440)*(date.getHours()*60+date.getMinutes()));
var zakazPeople=Math.round(totalPeople*0.1564);
var nowPeople=getRandom(10,50);
$('.totalPeople').text(totalPeople);
$('.zakazPeople').text(zakazPeople);
$('.nowPeople').text(nowPeople);
});
$(window).load(function(){var obj=$('.content-right-recommend-container');
	var offset=obj.offset();
var topOffset=offset.top;
var leftOffset=offset.left;
var marginTop=obj.css("marginTop");
var marginLeft=obj.css("marginLeft");
$(window).scroll(function(){var scrollTop=$(window).scrollTop();
	if(scrollTop>=topOffset){obj.css({marginTop:0,left:leftOffset,top:0,position:'fixed',});
}if(scrollTop<topOffset){obj.css({marginTop:marginTop,left:0,position:'relative',});
}if(scrollTop>=10000){obj.css({marginTop:0,left:leftOffset,bottom:0,position:'fixed',});
}});
});
$(document).ready(function(){
	var flag=true;
	$(window).mouseout(function(e){if(e.pageY-$(window).scrollTop()<1&&flag==true){$('.fadepopup, .eoxp').fadeIn(300);
	$('.eeee').fadeIn(300);
flag=false;
}})});
$(document).ready(function(){$(".eeee").click(function(){$(".eeee").addClass("actsss");
	$(".fadepopup").addClass("actsss");
$(".fadepopup").removeClass("xxxc");
$(".eeee").removeClass("xxxc");
$(".hikj").removeClass("actss");
$("body").removeClass("modal-show");
});
});
window.onload=function(){jQuery(".user-city").text(''+ymaps.geolocation.city+'');
}